
local chunks  = {
    --PIXEL SCENE APPEND!
} 

--[[
local chunks = { --example structure
    ["0_0"] = {
        {
            path = "", --path to the pixel scene
            offsetx = 0, --offsetx within the chunk, ideally 0-511
            offsety = 0, --offsety within the chunk, ideally 0-511
        },
        {
            path = "mods/parallel_parity/files/autogenerated/kinda lame pixelscene.xml",
        },
    },
    ["-14_29"] = {
        {
            path = "mods/parallel_parity/files/autogenerated/todo: add pixel_scene name here.xml",
            offsetx = 22,
            offsety = 415,
        },
    },
}--]]


local old_init = init
init = function( x, y, w, h )
    old_init(x, y, w, h)

    local chunk = {x = x/512, y = y/512} --get chunk coordinates

    while chunk.x > map_width do --logic that relativises east PWs
        chunk.x = chunk.x - map_width
    end
    while chunk.x < 1 do --logic that relativises west PWs
        chunk.x = chunk.x + map_width
    end

    local chunk_table = chunks[chunk.x .. "_" .. chunk.y] --get chunk table
    if chunk_table then --if there is a chunk table
        for index, scene in ipairs(chunk_table) do --iterate over all pixel scenes in the table
            EntityLoad(scene.path, x + scene.offsetx, y + scene.offsety) -- load the pixel scene
        end
    end
end